version: "3.7"

services:
  drizzle-sandbox-postgres:
    image: postgres:14.5-alpine3.16
    container_name: drizzle-sandbox-postgres
    command: postgres -c stats_temp_directory=/tmp
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
